version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    ignore:
      - dependency-name: "pytest"
        versions: ["7.4.0"]
