name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Block .env files
      run: |
        if git diff --name-only origin/master..HEAD | grep -qE "^.env|^.env.sample|^.env.example"
        then 
          echo ".env files must not be committed" 
          exit 1
        fi
