name: Code Quality
on: [push, pull_request]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upgrade setuptools
      run: |
        pip install --upgrade setuptools

    - name: Purge pip cache
      run: pip cache purge

    - name: Install PyTorch
      run: |
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

    - name: Run isort
      run: |
        pip install isort
        isort . --check-only

    - name: Run Black
      run: |
        pip install black
        black --check .

    - name: Run Ruff
      uses: chartboost/ruff-action@v1
