name: Security Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    - name: Run Bandit
      run: bandit -r . --exclude ./tests/

  safety:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Safety
      run: |
        python -m pip install --upgrade pip
        pip install safety
    - name: Run Safety
      run: safety check -r requirements.txt
